# Generated by Django 4.1 on 2023-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="venue_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
