# Generated by Django 4.1 on 2023-07-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_employee_venue_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("NameLogin", models.CharField(max_length=255)),
                ("Password", models.CharField(max_length=20)),
                ("Faculty", models.CharField(max_length=255)),
                ("Image", models.ImageField(null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="receptionist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Password", models.CharField(max_length=20)),
                ("NameLogin", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("DateOfBirth", models.DateField(null=True)),
                ("Image", models.ImageField(null=True, upload_to="")),
                ("ExamDate", models.DateTimeField()),
                (
                    "DoctorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="medicalappointmentschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("Address", models.TextField()),
                ("Note", models.TextField()),
                ("ClinicForPatients", models.CharField(max_length=255)),
                (
                    "DoctorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
                (
                    "ReceptionistID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.receptionist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="historypatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Symptoms", models.CharField(max_length=255)),
                ("PreExamResults", models.CharField(max_length=255)),
                ("PreExamDate", models.DateTimeField()),
                (
                    "PatientID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="diseases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NameDiseases", models.CharField(max_length=255)),
                (
                    "DoctorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="diseaseprogression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CurrentStatus", models.CharField(max_length=255)),
                ("MedicationDosage", models.CharField(max_length=255)),
                ("DiseaseDevelopment", models.CharField(max_length=255)),
                (
                    "PatientID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NameOfDisease", models.CharField(max_length=255)),
                ("MRIImages", models.ImageField(null=True, upload_to="uploads/")),
                ("ResultByAI", models.TextField()),
                ("Date", models.DateTimeField()),
                ("ResultByDoctor", models.TextField()),
                (
                    "DoctorID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.doctor"
                    ),
                ),
                (
                    "PatientID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.patient"
                    ),
                ),
            ],
        ),
    ]
