# Generated by Django 4.1 on 2023-07-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_comment_inputimage_alter_comment_outputimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Date',
        ),
    ]
